2 play/pause
joac001/pomodoro_project_aninfo pull request #37
Opened 2023-11-16 15:27 UTC by mmosan

## Motivation
Closes #2 as it introduces a button that lets the user pause the timer.

## Summary of changes
Added pause button

## Test additions / changes

## Checklist
- [ ] Tested the changes locally.
- [ ] Reviewed the changes on GitHub, line by line.
- [ ] Unit tests added.
- [ ] This change requires new documentation.
- [ ] Documentation has been added/updated.

2023-11-16 20:04 UTC, levdevs requested changes
Buttons work as expected. However, issue states that the Play and Pause buttons should be the same, or otherwise, display one at a time. I've added a potential solution in the review.

2023-11-16 21:17 UTC, joac001 commented on src/components/timer.js
> +            <button onClick={this.stopTimer}>Pause</button>
I agree, i like the idea @mmosan

2023-11-17 14:34 UTC, joac001 approved these changes

2023-11-17 14:34 UTC, joac001 commented on src/components/timer.js
> +            <button onClick={this.stopTimer}>Pause</button>
I'm going t approve this pr, but we will keep this idea for a refactoring step.

2023-11-17 14:36 UTC, merged